### ISSUE TITLE
hCaptcha not working w/ Elementor Forms

### ISSUE THREAD

**Issue by coldxot** [hCaptcha/hcaptcha-wordpress-plugin#135] opened 2021-12-30 02:02 UTC
Been having an issue where my form widget editor is completely grayed out. As with any issue I went through and deactivated each plugin one by one and it seems this only occurs with this plugin active.

Also tried on a fresh install website w/ nothing but Elementor +Pro, Hello Elementor Theme, and this plugin. Error occurred immediately.

**Comment by kagg-design** [comment] 2022-01-15 16:20
@coldxot As I have answered on the wp.org https://wordpress.org/support/topic/hcaptcha-not-working-w-elementor-forms/#post-15255095, I cannot reproduce the issue. Could you send me .zip archive of the empty site, on which you see the bug?

Thank you.

**Comment by FriendlyGremlin** [comment] 2022-01-16 15:17
Hello,
Unfortunately, I am faced with the same issue. I don't know if it's helpful (not really good at coding or webpages), but the console on edge, when clicking on the form to edit it, produces the attached errors: [error message.txt](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/files/7877218/error.message.txt)
The error only occurs when "Enable hCaptcha on Elementor Pro Form" is activated, and only when trying to edit a "Forms" element. All other element properties display as normal, but when clicking on any form (either creating a new one or editing an existing one), the properties window on the left remains blank.
Versions used are Elementor v3.5.3 and Elementor Pro v3.5.2.
Thanks and best regards.

**Comment by kagg-design** [comment] 2022-01-16 16:46
I tried to reproduce the problem with Edge - no luck. WP 5.8.3, Elementor v3.5.3 and Elementor Pro v3.5.2, hCaptcha 1.13.3, standard 2021 theme.

Could you create a test site, on which I can see the bug and send a DB copy to me?

Thank you.

**Comment by FriendlyGremlin** [comment] 2022-01-16 20:39
Thanks for your efforts. Unfortunately, creating a full test site and exporting the DB are beyond my abilities, unless there's an easy guide to follow along somewhere?

For what it's worth, my setup is the same as yours, except my version of hCaptcha is 1.13.4.2 instead of 1.13.3. Also, the bug appears even when disabling all other plugins aside from hCaptcha, Elementor and Elementor Pro, and is present regardless of theme (tried Standard 2021 and Astra).

**Comment by kagg-design** [comment] 2022-01-17 07:12
I have tested with the latest version of hCaptcha, of course. What browser in which version do you use? Can you provide a link to your site?

**Comment by AKSpalva** [comment] 2022-01-25 15:43
Hi there,

I have the same problem on my website. The affected site is the form at https://akspalva.com/contact/

I'm also not sure how to create a copy of the website for you; I'm still pretty new at web design and wordpress. I also don't have all the steps I took to make it. However, I could create an editor user for you and provide you the credentials through some private channel. Let me know if that might help.

**Comment by skellenb** [comment] 2022-01-31 18:12
when commenting lines 69-74 in /src/php/ElementorPro/HCaptchaHandler.php then it might work

**Comment by AKSpalva** [comment] 2022-02-05 09:12
> when commenting lines 69-74 in /src/php/ElementorPro/HCaptchaHandler.php then it might work
This did work in restoring functionality, but unfortunately, I don't see a way to add hCaptcha to the form now (nothing about the Elementor Pro settings has changed, from what I can see). Unless I'm missing something?

**Comment by kagg-design** [comment] 2022-04-17 13:55
Closed as non-reproducible.

**Comment by kagg-design** [comment] 2022-08-27 19:26
There is an issue with "Turn off when logged in" - thank you for noticing. I have fixed it in v1.18.0. We will publish it in August.

**Closed by kagg-design** 2022-08-27 19:26 UTC
Labels: bug, cannot-repro

**Comment by kagg-design** [comment] 2022-08-30 08:06
@coldxot @FriendlyGremlin @AKSpalva @skellenb @drangam, with the help of @MarkWest2017, I have reproduced and fixed the issue. v1.19.0 should be released today, 30-Aug.
