### ISSUE TITLE
[hCaptcha] Missing sitekey but the sitekey is entered

### ISSUE THREAD

**Issue by Filip785** [hCaptcha/hcaptcha-wordpress-plugin#56] opened 2020-12-02 22:26 UTC
Hi,

I installed this plugin on one of the websites I maintain, but the integration with CF7 does not seem to work. The checkbox gets rendered in form but it doesn't work and gives [this messages in the console](https://ibb.co/ZLqtt6H), implying that sitekey is not entered, but it is entered in wp-admin. Also the pages where there are contact forms never fully finish loading the key in tab just keeps spinning.  Also, I have the captcha enabled to wordpress login page as well and it is working perfectly, but on contact form it's not.

Could you help please?

EDIT: Also, at times [this error](https://ibb.co/0BPgvsy) displays as well, which is weird because the page contains only 1 contact form. It doesn't show always, but sometimes page finishes loading but it displays the error additionally together with other 2 previously outlined.

**Comment by e271828-** [comment] 2020-12-03 00:22
@kagg-design can you take a look when you have a chance?

**Comment by kagg-design** [comment] 2020-12-08 19:45
@Filip785 @e271828- I cannot replicate this, please see that everything works on my test site: https://prnt.sc/vyijv9

Issue by itself looks like CF7 does not work by itself, and symptoms are similar to the case when REST is blocked.

Concerning error with 2 forms, I also have no idea. It is better to look at the site. If @Filip785 can share credentials (not here, but on my email,m which can be found in my profile, I will try to help).

**Comment by kagg-design** [comment] 2021-07-03 14:14
Closed as non-reproducible.

**Closed by kagg-design** 2021-07-03 14:14 UTC
